spring:
  task:
    scheduling:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

nonnas:
  rate-limit:
    enabled: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    com.nonnas: WARN
    org.springframework: WARN
    io.zonky: INFO
